# Generated by Django 3.1.3 on 2020-11-28 11:35

from django.db import migrations, models
import police.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, validators=[police.models.validate_mobile])),
                ('police_station', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
    ]
