# Generated by Django 3.1.3 on 2020-12-26 07:51

import datetime
from django.db import migrations, models
import police.models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=1)),
                ('dob', models.DateField(validators=[police.models.validate_age])),
                ('mobile', models.CharField(max_length=10, validators=[police.models.validate_mobile])),
                ('street', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('eye_colour', models.CharField(max_length=40)),
                ('hair_colour', models.CharField(max_length=40)),
                ('skin_tone', models.CharField(max_length=40)),
                ('possible_suspect1', models.CharField(blank=True, default='', max_length=40)),
                ('possible_suspect2', models.CharField(blank=True, default='', max_length=40)),
                ('comments', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='police',
            old_name='police_station',
            new_name='police_station_id',
        ),
        migrations.AddField(
            model_name='police',
            name='dob',
            field=models.DateField(default=datetime.date(1980, 1, 1), validators=[police.models.validate_age]),
        ),
    ]
