# Generated by Django 3.1.3 on 2020-12-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_auto_20201226_0751'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='police',
            table='police_officers',
        ),
        migrations.AlterModelTable(
            name='victim',
            table='victims',
        ),
    ]
