# Generated by Django 3.1.3 on 2020-12-27 18:51

from django.db import migrations, models
import django.db.models.deletion
import police.models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_auto_20201226_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('street', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'police_stations',
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sex', models.CharField(max_length=1)),
                ('dob', models.DateField(validators=[police.models.validate_age])),
                ('mobile', models.CharField(max_length=10, validators=[police.models.validate_mobile])),
                ('street', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'suspects',
            },
        ),
        migrations.RemoveField(
            model_name='victim',
            name='possible_suspect1',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='possible_suspect2',
        ),
        migrations.AddField(
            model_name='police',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='victim',
            name='comments',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='Sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('date_time_sighting', models.DateTimeField(blank=True, null=True)),
                ('victim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.victim')),
            ],
            options={
                'db_table': 'sightings',
            },
        ),
        migrations.AddField(
            model_name='victim',
            name='police_station_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='police.policestation'),
        ),
        migrations.AddField(
            model_name='victim',
            name='possible_suspects',
            field=models.ManyToManyField(to='police.Suspect'),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.policestation'),
        ),
    ]
