# Generated by Django 3.1.4 on 2021-01-09 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import police.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('police', '0005_police_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='messages',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='status',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[police.models.validate_mobile]),
        ),
    ]
