# Generated by Django 3.1.4 on 2021-01-09 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0007_remove_victim_possible_suspects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='police_station_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='police.policestation'),
        ),
    ]
