# Generated by Django 3.1.4 on 2021-01-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0008_auto_20210109_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='date_time_sighting',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Choose date and time of sighting'),
        ),
    ]
