# Generated by Django 3.1.4 on 2021-01-10 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0010_auto_20210109_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='police',
            options={'verbose_name_plural': 'police_officers'},
        ),
        migrations.AlterModelOptions(
            name='policestation',
            options={'verbose_name_plural': 'police_stations'},
        ),
        migrations.AlterModelOptions(
            name='sightings',
            options={'verbose_name_plural': 'sightings'},
        ),
        migrations.AlterModelOptions(
            name='suspect',
            options={'verbose_name_plural': 'suspects'},
        ),
        migrations.AlterModelOptions(
            name='victim',
            options={'verbose_name_plural': 'victims'},
        ),
        migrations.AddField(
            model_name='suspect',
            name='police_officer_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='police.police', verbose_name='Interrogated By'),
        ),
        migrations.AddField(
            model_name='victim',
            name='police_officer_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='police.police'),
        ),
        migrations.AddField(
            model_name='victim',
            name='suspect_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='police.suspect'),
        ),
    ]
