# Generated by Django 3.1.4 on 2021-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0011_auto_20210110_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='victim',
            name='messages',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='status',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
