# Generated by Django 3.1.4 on 2021-01-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0013_victim_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='input_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
