# Generated by Django 3.1.4 on 2021-01-15 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0015_input_image_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_image',
            name='placeholder',
        ),
    ]
