# Generated by Django 3.1.4 on 2021-01-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0016_remove_input_image_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_input_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads')),
                ('img_type', models.CharField(choices=[('Suspect', 'suspect'), ('Victim', 'victim')], default='Suspect', max_length=20)),
            ],
        ),
    ]
