# Generated by Django 3.1.4 on 2021-01-30 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0017_other_input_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_image',
            name='image',
            field=models.FileField(upload_to='uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
        migrations.AlterField(
            model_name='other_input_image',
            name='img_type',
            field=models.CharField(choices=[('suspect', 'Suspect'), ('victim', 'Victim')], default='suspect', max_length=20, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])]),
        ),
    ]
