# Generated by Django 3.1.4 on 2021-02-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0019_auto_20210130_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='input_image',
        ),
        migrations.DeleteModel(
            name='other_input_image',
        ),
    ]
