# Generated by Django 3.1.4 on 2021-02-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0020_auto_20210203_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='key',
            field=models.CharField(blank=True, default='0000', max_length=4, null=True),
        ),
    ]
